site_name: Agent Test
theme:
  name: material
  palette:
    - scheme: Default
      primary: "rgb(9, 12, 45)"
      accent: "rgb(9, 12, 45)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: "black"
      accent: "black"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.mark
  - md_in_html

extra_css:
  - styles/custom.css

nav:
  - Installation Guide: setup.md
  - Agent Test: index.md
