site_name: PatternAI Labs Docs
site_url: http://localhost:8002/
site_description: Documentation for the Pattern AI Agent Test Project
extra:
  homepage: http://localhost:8000/

theme:
  name: material
  palette:
    - scheme: Default
      primary: "rgb(9, 12, 45)"
      accent: "rgb(9, 12, 45)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: "black"
      accent: "black"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.mark
  - md_in_html
extra_css:
  - styles/custom.css
nav:
  - Home: index.md
  - Projects:
      - Back to projects: projects.md
      - Agent Test:
          - Installation Guide: setup.md
          - Agent Test: developer.md
plugins:
  - search
  - minify:
      minify_html: true
